@startuml
node gNB {
    node CU {
        node "CU-C"
        node RRC
        node "CU-M"
        node "CU-U"
    }
    node DU
    node RU
    RRC .- DU: Fs-HL-C/F1-C
    (CU-M) -- DU: Fs-HL-M/F1/F1-M
    (CU-U) -- DU: Fs-HL-U/F1/F1-U
    DU -- RU:Fs-LL
}
node EPC
node eNB
node UE

UE .- EPC: NAS
gNB .- eNB: X2
gNB -- UE: 5G-Uu(Uplane)
gNB .- UE: 5G-Uu(Cplane)
(CU-C) .- EPC: S1-C/NG1
(CU-U) -- EPC: S1-U/NG1
@enduml